### ISSUE TITLE
Fix PyPI description issues.

### ISSUE THREAD

**Issue by nasirhjafri** [nasirhjafri/libyear#10]
While uploading releases to PyPI read me file is used which looks weird on PyPI. We need a way to fix i.

**Comment by ibLeDy** [comment]
Hi, you take a look at the PyPi docs, they mention it [here](https://pypi.org/help/#description-content-type), but hey refer to the [Packaging Docs](https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py). This is what they suggest: `long_description_content_type="text/markdown"`

I would also suggest using a context manager [here](https://github.com/nasirhjafri/libyear/blob/master/setup.py#L9), as it is the "proper" way to do so.
It is a simple change and it will close the file for you.
```py
with open("README.md", "r") as f:
    long_description = f.read()

long_description=long_description
```

PD: I was just looking for some simple issues i can contribute to, but a PR would require more effort than this so i hope it is somewhat useful!

**Comment by nasirhjafri** [comment]
Hi @ibLeDy , thanks for the suggestion. I'll try it and create a PR.

**Comment by ibLeDy** [comment]
Sounds awesome! 

Here's a bit of context about the `with` statement:
https://docs.python.org/3/reference/compound_stmts.html#with

And about `context managers`:
https://docs.python.org/3/reference/datamodel.html#context-managers
