### ISSUE TITLE
feature: sort based on libyears behind

### ISSUE THREAD

**Issue by miketheman** [nasirhjafri/libyear#17]
As a user
Given a long libyears behind listing
When I want to prioritize some of the oldest deps
Then I should be able to sort the output accordingly

Considering the table is a PrettyTable, and there's both `.sortby` and `.reversesort` methods, this seems like it would be pretty straightforward to include.

Is this something you'd be interested in adding? I can imagine either a default sort, or allowing the user to control the sort - alphabetically too! I'd be happy to work on this.

**Comment by nasirhjafri** [comment]
Hi @miketheman , thanks for the suggestion. Would you like to open a PR?
