### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by miketheman** [nasirhjafri/libyear#20]
Many open source software packages have a license for users to evaluate whether they may use the software package in their application or tooling.

https://choosealicense.com/ is a great resource to leverage to understand what's available.

I am partial to https://choosealicense.com/licenses/mit/ -  but most of them are pretty standard. The MIT is also one of the most popular, as reported by WhiteSource: https://resources.whitesourcesoftware.com/blog-whitesource/open-source-licenses-trends-and-predictions

Once chosen, this can be added to `setup.py` like this:

```
    classifiers=[
        ...
        "License :: OSI Approved :: MIT License",
        ...
    ],
```

Other values can be found here: https://pypi.org/classifiers/

**Comment by zoofood** [comment]
Totally agree on this, even though its just a fun project to use, many developers in orgs can't even download it full stop without a license.

**Comment by miketheman** [comment]
Thanks @nasirhjafri !
